#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Far Beyond The Stars

# Short bio or description (displayed in the header)
description: You are the dreamer and the dream.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.farbeyondthestars.com/images/farbeyondthestars-avatar-2.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-144215-25

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.farbeyondthestars.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcastSite: http://www.travisneilson.com

# The cover image for the podcast, will show in search results in iTunes
podcastCoverImg: http://wwww.YourSite.com/imageSize1400x1400-min.jpg

# The name of your podcast
podcastTitle: My Podcast Title

# About You. For iTunes admin. This information is not displayed on the iTunes Store.
podcastOwner: YourName
podcastEmail: your@email.com

# See https://www.apple.com/itunes/podcasts/specs.html near the bottom for valid categories
category: Education
subCategory: Higher Education

# is it too dangerous for the impressionable kiddos?
podcastIsExplicit: "no"


podcastAuthor: Org, brand or individual
podcastDescription: Verbose description of the podcast.
podcastSubtitle: Short description of the podcast - 255 character max.



#                          ###



# Don't edit below this line unless you know what you are doing.
# ------------------------------------------------------------------------


# Create a Jekyll collection to handle the episodes
collections:
- episodes

# Identify a place to output the generated files
destination: _upload-this

# Keep the readme out of the output folder
exclude: ['readme.md']


#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
